### ISSUE TITLE
Question about image object in metadata

### ISSUE THREAD

**Issue by dohomi** [juliancwirko/nft-art-maker#16]
Hello

I have a question about the metadata generation. Is that object allowed for OpenSea? Inside the OpenSea documentation they list `image` as a string reference, while your output is an object.

Thanks for clarification

**Comment by juliancwirko** [comment]
Hey, I don't know opensea much, but if so, then it probably won't be compatible. There will be an option to define the structure: https://github.com/juliancwirko/nft-art-maker/issues/7

**Comment by juliancwirko** [comment]
I'll try to work on this one today

**Comment by juliancwirko** [comment]
in 5.2.0 there is now a possibility to define the metadata structure: https://github.com/juliancwirko/nft-art-maker#output-metadata-schema-configuration

**Comment by dohomi** [comment]
thanks for the update!
