### ISSUE TITLE
Make the metadata fields optional where it is possible

### ISSUE THREAD

**Issue by juliancwirko** [juliancwirko/nft-art-maker#24]
The nft-art-maker can generate different metadata structures based on required fields and configuration of the metadata mapper (check docs). Still, sometimes it won't be necessary to reuse all fields. This task would be to identify dependencies on all fields and make as many optional fields as possible.

**Comment by dohomi** [comment]
@juliancwirko I improved all `edition` requirements inside of #21 I don't think that any other metadata field was optional - all other fields are required in my opinion.
