### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by JezasBam** [juliancwirko/nft-art-maker#28]
A bunch of errors in terminal .

**Comment by juliancwirko** [comment]
Hi, yes seems so. It needs some updates, etc. 
For now, I've updated the `canvas` lib. Try `v6.0.1`. It is already published in the npm registry.
It should work on Node 18.* now.
I checked in the example directory, and it works.

I'll try to find some more time and update all other dependencies. It may be tricky in some cases.

**Comment by JezasBam** [comment]
You have all the time in the world, I just wanted to let you know that it doesn't work and I at least wanted to test things :))

I'm happy to see you active , I'm really trying to learn what you created , you are a GENIUS !

I don't have any programming experience but apparently I know how to edit and I don't give up trying to learn what you created, here are 2 examples of what I created using what you provided and I will continue to learn because what you do is much easier to use than MultiversX sdk !
