### ISSUE TITLE
failed npm install

### ISSUE THREAD

**Issue by tricastor** [juliancwirko/nft-art-maker#8]
Hello,
I have an issue installing nft-art-maker:
$ sudo npm install -g nft-art-maker

npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /usr/lib/node_modules/nft-art-maker/build/index.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/lib/node_modules/nft-art-maker/build/index.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-02-28T10_51_45_633Z-debug.log

the log says:
371 error code ENOENT
372 error syscall chmod
373 error path /usr/lib/node_modules/nft-art-maker/build/index.js
374 error errno -2
375 error enoent ENOENT: no such file or directory, chmod '/usr/lib/node_modules/nft-art-maker/build/index.js'
376 error enoent This is related to npm not being able to find a file.
377 verbose exit [ -2, true ]

indeed, the path /usr/lib/node_modules/nft-art-maker/build/ does not exist on my installation...

**Comment by juliancwirko** [comment]
Please try to use it with global installation `npm install -g nft-art-maker` or with [nvm](https://github.com/nvm-sh/nvm) if that's not working. This is probably something with the Node configuration on your OS.

**Comment by tricastor** [comment]
Great ! I fixed it by installing nvm:
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
nvm install node
nvm use node
and then installing after cleaning npm cache:
npm cache clean
npm install -g nft-art-maker

thank you @juliancwirko !
