### ISSUE TITLE
example folder would be good for self-explain a project setup

### ISSUE THREAD

**Issue by dohomi** [juliancwirko/nft-art-maker#9]
Hi there,

I found your repo and its great to wrap everything into one npm repo! I suggest to create an example folder with some example project, that would make it easier to jumpstart into a new project. Just a suggestion, for example its not really clear for me what is the most basic setup to kickstart a new project because there is a huge configuration possibility.

Cheers!

**Comment by juliancwirko** [comment]
Hey, this is an excellent idea. I'll add it. Thanks.

**Comment by juliancwirko** [comment]
added: https://github.com/juliancwirko/nft-art-maker/tree/main/example

**Comment by dohomi** [comment]
awesome thanks

**Comment by dohomi** [comment]
@juliancwirko as nft.storage is mentioned inside of the readme, could the script uploading the generated file be part of the example? That would show a full roundtrip to users to see the huge benefit to conveniently use this package and upload the data directly.
